# -*- coding: utf-8 -*-
"""diet_and_exercise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fth7ZOCsy3zaLUf1qIVpO1gV9md6SegA
"""

import pandas as pd
data=pd.read_csv("/content/diet and exercise.csv")

red = '\033[91m'
green = '\033[92m'
blue = '\033[94m'
bold = '\033[1m'
italics = '\033[3m'
underline = '\033[4m'
end1 = '\033[0m'
def sugg(health,diabetic):
  for index, row in data.iterrows():
    if row['Body Health'] == health and row['Diabetic'] == diabetic:
      diet = row['Diet']
      exercise = row['Exercise']
      print(bold+underline+"DIET:"+end1,end="\n")
      print(diet)
      print(bold+underline+"EXERCISE:\n\n"+end1+exercise)

sugg('malaria','type1')